name: Beyond Beauty
favicon: null
layout_spectrum: 0.09024751465767622
typography_spectrum: 0.15413657436147332
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.9712190481368452
  lightness: 0.8985603793989867
  saturation: 0.2962450080085546
  rhythmicContrast: 0.34858995233662426
purpose: []
